name: Run Gemini CLI

on:
  workflow_dispatch: # allows manual trigger

jobs:
  run-gemini:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Gemini CLI
        run: npm install -g @google/gemini-cli

      - name: Run Gemini CLI Help
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: gemini --help

      - name: Ask Gemini a Question
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          gemini chat "Hello Gemini, give me a short motivational quote"
